/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.hvl.dat250.mathiasskauge.exp1;

import io.javalin.Javalin;
public class App {

    private static final String WEBPAGE = "<!DOCTYPE html>\n" +
            "<html lang=\"en\">\n" +
            "<head>\n" +
            "    <meta charset=\"UTF-8\">\n" +
            "    <title>Convert units</title>\n" +
            "</head>\n" +
            "<body>\n" +
            "<h1>Unit converter</h1>\n" +
            "<form action=\"/convert\" method=\"post\">\n" +
            "    <fieldset>\n" +
            "    <label for=\"val\">Value:</label>" +
            "    <input id=\"val\" type=\"text\" name=\"value\"><br />\n" +
            "    <label for=\"source-unit\">From unit:</label>\n" +
            "    <select name=\"sunit\" id=\"source-unit\">\n" +
            "        <option value=\"in\">Inches</option>\n" +
            "        <option value=\"ft\">Feet</option>\n" +
            "        <option value=\"mi\">Miles</option>\n" +
            "        <option value=\"m\">Metres</option>\n" +
            "    </select><br />\n" +
            "    <label for=\"target-unit\">To unit:</label>\n" +
            "    <select name=\"tunit\" id=\"target-unit\">\n" +
            "        <option value=\"in\">Inches</option>\n" +
            "        <option value=\"ft\">Feet</option>\n" +
            "        <option value=\"mi\">Miles</option>\n" +
            "        <option value=\"m\">Metres</option>\n" +
            "    </select><br />\n" +
            "    <input type=\"submit\" value=\"Calculate\" />\n" +
            "    </fieldset>\n" +
            "</form>\n" +
            "</body>\n" +
            "</html>";

    private static final double IN_TO_METER = 0.0254;
    private static final double FT_TO_METER = 0.3048;
    private static final double MI_TO_METER = 1609.344;


    public static void main(String[] args) {
        Javalin.create()
                .get("/", ctx -> {
                    ctx.html(WEBPAGE);
                })
                .post("/convert", ctx -> {
                    double value = Double.parseDouble(ctx.formParam("value"));
                    String fromUnit = ctx.formParam("sunit");
                    String toUnit = ctx.formParam("tunit");

                    double result = convert(value, fromUnit, toUnit);

                    ctx.result(Double.toString(result));
                })
                .start(9000);
    }

    /**
     *Performs unit conversions (feet to meter, inch to feet etc.).
     * @param value the number you want to convert
     * @param fromUnit the unit you want to convert from
     * @param toUnit the unit you want to convert into
     * @return Result of conversion
     */
    public static double convert(double value, String fromUnit, String toUnit) {
        double inMeters;
        switch (fromUnit) {
            case "in":
                inMeters = value * IN_TO_METER;
                break;
            case "ft":
                inMeters = value * FT_TO_METER;
                break;
            case "mi":
                inMeters = value * MI_TO_METER;
                break;
            case "m":
                inMeters = value;
                break;
            default:
                inMeters = Double.NaN;
                break;
        }
        switch (toUnit) {
            case "in":
                return inMeters / IN_TO_METER;
            case "ft":
                return inMeters / FT_TO_METER;
            case "mi":
                return inMeters / MI_TO_METER;
            case "m":
                return inMeters;
            default:
                return Double.NaN;
        }
    }

}






